apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-demo
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io

spec:
  project: poc-demo

  source:
    repoURL: https://github.com/nimya2007/nginx-helm-chart.git
    targetRevision: main
    path: .

  destination:
    server: https://kubernetes.default.svc
    namespace: demo-nginx

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true